# -*- coding: utf-8 -*-
"""json_to_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WC671Ys-cDtChPMl99-RPWPxr3kdyPp-
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('drive/MyDrive/DeepFake')

import pandas as pd
#str(i)
for i in range(1, 2):
    path_json = "data/train_sample_dfdc"+"/metadata.json"
    path_csv = "data/train_sample_dfdc"+"/metadata.csv"
    print(path_csv)
    print(path_json)
    read_json = pd.read_json(path_json)
    df = pd.DataFrame(read_json)
    df_2 = pd.DataFrame(df.transpose())
    df_2.to_csv(path_csv)
    read_csv = pd.read_csv(path_csv)
    read_csv.columns = ["URI","label","split","original"]
    read_csv.to_csv(path_csv,index=False)
    print(read_csv.head(5))

